apiVersion: v1
kind: ConfigMap
metadata:
  name: helmconfig
  namespace: jobs-cron
data:
  name: "Hello Aniket"
  {{- with .Values.games }}
  name: {{ .name | upper }}
  part: {{ .part | upper }}
  {{- end }}
  list: |-
    {{- range .Values.gamelist }}
      {{ . | upper | quote }}
    {{- end }}
